version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: vuln_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./docker/php
    container_name: vuln_php
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0
    container_name: vuln_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vuln_app
      MYSQL_USER: vuln_user
      MYSQL_PASSWORD: vuln_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  db_data: